Update tsconfig.json
 please add this prop  ("skipLibCheck": true) because there is annoying error (node_modules/class-validator/validation/Validator.d.ts:383:38 - error TS2503: Cannot find namespace 'ValidatorJS'.)